name: Update Repo
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: update data
        run: |
          python scripts/fetch.py
      - name: draw map
        run: |
          python scripts/map.py
      - name: commit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "elecciones-bot@example.com"
          git config --global user.name "elecciones-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualización"; git push -q "https://$GH_TOKEN@github.com/mauforonda/elecciones2020.git" master)
